Source/MindTheWord.js
Source/background.js
Source/options.js

As per our conversation I am sending this PR.
Please guide me if I am not going in the right direction.

Improving Javascript style

---

Source/MindTheWord.js

Words in links got translated due to a problem in the code.
I changed:
!!badTags.indexOf(node.tagName)
to:
!(badTags.indexOf(node.tagName) > -1)

Fixed translate in links

---

Source/options.js

Fixing issue reported by multiple users, here is one user description:-
Donald Rice II Modified Apr 6, 2015
If you select " Do not Translate," the Extension will forever not work, and you can not create another option to make it work (I was having problems changing things to Japanese until I tried doing that without hitting " do not translate."
Please fix this bug!

Fix Bug: If you select 'Do not Translate', the Extension stop working

---

Source/background.js
Source/options.html
Source/options.js

Haven't tested the changes for all languages only tested it for french.
Some issue remaining:-
The set of languages supported by different services is different so need some way to validated the languages that can be added for translation.
Need to have a map for language to its short form like french to fr, since for some languages it is different for google translate and yandex.
Since google translate is currently not working because it is blocking calls I guess this will be good workaround for some users like me atleast.

Adding option to pick yandex as a translation service.

---

Source/options.js

When a user creates the same pattern again, this fix raises a warning and does not allow duplicate creation.
> This is good. Avoiding creating repeated translation patterns is good. Remember to warn the user that a new pattern has not been created because it already exists.
I have put the warning.
>This is not good. It is ok to have two patterns with the same languages and different probabilities. For instance, if I am learning Russian, I could be interested in having two translation patterns from English to Russian: one with low probability, for everyday use; and one with high probability, when I really want to study Russian harder.
I have made the changes suggested. Now same languages with different probabilities can be created.
This change was initially in pull request #65.

fix duplicate pattern input in createPattern function

---

Source/MindTheWord.js
Source/options.js
Source/popup.html

**In reference to #62**
I think this was the reason why some people thought that the extension wasn't working. In the file **options.js** there is a function **save**. Earlier there was no separate check for a checkbox in the function due to which **v was defaulting to a string on**. 
The default string value caused the **main** function in MindTheWord.js to always default to the option with **limitToUserDefined**
But the default value for **limitToUserDefined**  is set to **{"the":"the", "a":"a"}**. There is a check in the **function processTranslations** which filters such translations. 
The check I have added ensures that the current value of the limit to user defined translations checkbox gets through. After making this edit the extension is working perfectly fine for me

Issue with user defined translations

---

Source/options.js

In the function, we have to check for storage not initialized as well as check if the object data has fields other activation or not. This fix checks for the `savedPatterns` field. 
Fixes issue #39.

fix loadStorageAndUpdate function

---

Source/options.js

In function `createPattern`, the variable `pattern` was accessing undefined `savedPatterns` from the local storage. This is fixed by adding a simple check.

fixed options pages

---

Source/background.js
Source/options.html
Source/options.js

Default translator set to Yandex as discussed in #81 
Yandex does not support translation to Latin, so it has been changed to German in the default case.

default translator set to Yandex

---

Source/background.js
Source/options.js

Update #84.
User can save translated words to the dictionary using context menu:

Saving words to user dictionary. UPD

---

Description.md
Source/_locales/es/messages.json

In Description.md: This improves the Spanish translation and updates the English to account for characters as well as words. Also, "Laothain" is not a language, but Laotian is.

Rewrite Spanish, edit English in Description

---

.travis.yml
CONTRIBUTE.md
karma.conf.js
lib/scripts/controllers/options.js
lib/scripts/controllers/popup.js
lib/scripts/mtw.js
package.json
test/specs/background.js
test/specs/contentScript.js
test/specs/options.js
test/specs/popup.js

Unit Testing
----------
Include unit testing using `jasmine` and `karma`. It tests all the files independently and verifies its functionality. 
To run the tests
```shell
npm i -g gulp-cli
npm install
npm test
```
You should see a screen like this:
Right now many of the tests are empty. Over time, we will fill the test cases.
Travis CI
--------------
This PR also completes the `travis.yml` file required for checks to pass. I expect it to work as I cannot test without pushing rights to the repo. If this script works, all the PRs will be tested for these tests and if any of the tests fail, it will show a cross.
**Note:** Travis CI needs to be tested.

Unit testing and Travis CI file

---

lib/scripts/controllers/options.js
lib/scripts/filters/startFrom.js
lib/styles/main.css
lib/views/options.html

It limits to 4 entries per page and automatically creates new pages as per the entries.

pagination for blacklisted words and websites

---

lib/scripts/controllers/options.js
lib/scripts/mtw.js
lib/scripts/utils/http.js
lib/views/options.html

This PR fixes 2 bugs:
1. Undefined args in `http.js` #125 
2. Delete pattern - If the user deletes an active pattern. It gets removed from the UI but MTW still translates using the old activation data.

Delete pattern bug

---

lib/scripts/eventPage.js
lib/scripts/mtw.js
lib/scripts/services/contextMenu.js
lib/views/options.html

Now words can be put into different difficulty level buckets, this will help the user differentiate between the words he should concentrate on and the ones he knows well
Three colors have been reserved for the easy, normal and difficult buckets:
The user can select the word and chose which bucket to put it into using the context menu: 
Next time when the words appear, they will appear in their respective difficulty colors:

Difficulty buckets in context menu

---

lib/scripts/eventPage.js
lib/scripts/services/contextMenu.js

Context menus are disabled automatically for blacklisted pages, `chrome://` and blank URL pages. So we don't need to check `isValid` condition every time.

Auto disable context menu

---

lib/assets/css/MTWStyles.css
lib/scripts/eventPage.js
lib/scripts/mtw.js
lib/scripts/services/bingTranslate.js
lib/scripts/services/contextMenu.js
lib/scripts/services/googleTranslate.js
lib/scripts/services/yandexTranslate.js

This PR adds the following functionality:
1. **Sentence Translation:** User can select a sentence (3 - 15 words) and click `Translate Sentence` from context menu to get the translation of that sentence. This translation will be shown as a popover above the selection. It can be dismissed with a click.
2. **Modular CSS:** If any style has to injected in a webpage, it can be directly added to `MTWStyles.css`. This will be automatically added - no need for other injection.

Sentence translation

---

lib/styles/main.css
lib/views/options.html

This PR commits the following
1. Divide navigation bar into sections
2. Add blank panel messages
3. Add help popovers

UI modifications

---

lib/scripts/eventPage.js
lib/scripts/mtw.js
lib/scripts/services/yandexTranslate.js

Fix 2 bugs:
1. In pages which did not have any stylesheet (rather old ones), the translated words were not highlighted. 
2. On toggling the activation to 'Off' on any particular page, the context menu was not disabled.

Minor fixes

---

lib/scripts/mtw.js

If an HTML tag (with nodetype `TEXT_NODE`) was passed to the function, it would replace it with a blank string. This led to data loss and UI breaks. This PR fixes the issue by adding a check for empty `newText` variable.

fix empty replacements

---

lib/scripts/utils/defaultStorage.js
lib/views/includes/advanced.html

I have added the keys panel in the **advanced tab** instead of the *translation tab* because there is already a field of keys there. It would cause confusion to the user.
Please suggest changes if needed.

keys panel in advanced tab

---

lib/scripts/mtw.js
lib/scripts/services/bingTranslate.js
lib/scripts/services/yandexTranslate.js

1. Empty blacklist caused all websites to be blacklisted
2. Empty blacklist word list causes all words to be blacklisted
3. Some errors generated were not properly caught

Fix and catch errors 

---

config.js
lib/scripts/controllers/options.js
lib/scripts/mtw.js
lib/scripts/utils/defaultStorage.js
lib/views/includes/translation.html
package.json

This PR adds functionality to translate one word in each sentence.
It is significantly faster than the `replaceAll` function. Users can create a pattern and toggle the button if they want one word to be translated in each sentence. Clicking on the button again turns it off.

Translate one word per sentence
