Source/MindTheWord.js, Source/background.js, Source/options.js, Source/popup.js, Tests/beforeeach.js, Tests/filterWords.test.js
#35 
Working on fixing the names of the identifiers to camel case 
Changed " " -> ' '
Fixed spacing
Inserted semi-colons
=>  Improve javascript style (Google style guide)

Source/MindTheWord.js, Source/background.js, Source/manifest.json, Source/options.js
This is in reference to #17 and #26: 
Added context menu for easy funtionality
Check for duplication
Add * to check for all sub domains
=> Make it easy to blacklist current site (#17)

Source/options.js
Currently the checkboxes are being skipped while restoring values as **elem.tagName.toLowerCase()** incase of checkboxes returns **input** and **elem.value = something** does nothing
=> [Fix] Restore value for checkboxes

Source/options.js
In reference to your conversation in PR #17
=> Added a ToDo in options.js as discussed in #17

Source/MindTheWord.js, Source/background.js, Source/options.js, Source/popup.js
This updates curly braces and indentation styling according to [Google style guide](https://google.github.io/styleguide/javascriptguide.xml?showone=Code_formatting#Code_formatting) in all the js files in source.
>Because of implicit semicolon insertion, always start your curly braces on the same line as whatever they're opening. 
``` 
if (something) {
// ...
} else {
// ...
}
```
> Multiline array initializers and object initializers are indented 2 spaces
It also fixes missing semicolons and replaces `!=` with `!==` wherever required i.e. comparing with zeroes and null. 
Improves javascript style #60
=> update styling according to Google styleguide

Source/background.js, Source/options.js
@Ceilican ,the master has split up. While I am figuring that out, you can add the feature using this PR.
=> [Enhancement] User can blacklist words using context menu

Source/MindTheWord.js, Source/popup.js
The `popup.js` file was raising an undefined function error on clicking the icon and toggle button. As a result toggle was not working.
There were two errors
1. In `popup.js` the function `toggleAllElements` was not called correctly.
2. In `MindTheWord.js` the function `__mindtheword` had bugs.
The errors have been resolved and toggle is now working.
=> fix undefined function error in popup

Source/options.js
Added a translation provider check during the check for duplicateInput in createPattern().
Follow up on [this issue](https://github.com/OiWorld/MindTheWord/issues/90).
=> PR to fix the issue of the same configuration with different translation providers.

Source/_locales/en/messages.json, Source/_locales/hi/messages.json, Source/options.html, Source/options.js
=> Added support for hindi

Source/options.html, Source/popup.html
> Indent by 2 spaces at a time.
Don’t use tabs or mix tabs and spaces for indentation.
> Although fine with HTML, do not close void elements, i.e. write `<br>`, not `<br />`.
=> update html styling according to Google style guide

Source/MindTheWord.js
addressing issue 18: https://github.com/OiWorld/MindTheWord/issues/18
see my approach/explanation here: https://github.com/OiWorld/MindTheWord/issues/18#issuecomment-196499717
=> making a fix for issue 18 by sorting the sourceWords in replaceAll

Source/MindTheWord.js
#37 fixed. Please see the issue for explanation.
=> Amount of Translations fixed

Source/options.js
=> Add validation for Block/Unblock at the end of the Yandex API key

Source/options.js
#106 
@Ceilican, this seemed like a much better idea
=> silently validate yandex key and remove anything after the first space

Source/options.html
I have added a fix for the current version. Will keep this in mind for the new UI. #111
=> change yandex key bar

lib/scripts/controllers/options.js, lib/views/options.html
1. As @rohankatyal29  suggested the box sizes are now fixed. 
2. It adds checks for blank inputs. 
3. Minor UI fixes.
=> Options page enhancements

lib/scripts/controllers/options.js, lib/styles/main.css, lib/views/options.html
Pagination for the user defined translations. It converts the object of `userDefinedTranslations` into list `userDefinedTranslationList` to enable pagination.
=> user defined translations pagination

lib/manifest.json, lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js, lib/views/options.html
=> Feature to speak words

lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js
=> Show word usage examples

lib/scripts/eventPage.js, lib/scripts/mtw.js, lib/scripts/services/contextMenu.js, lib/views/options.html
Changed: 
- Color names for difficulty buckets in options 
- Alert message for when current website is blacklisted or MTW is switched off 
- Fixed bug introduced while merging
=> Minor code refactoring

lib/manifest.json, lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/mtw.js, lib/scripts/services/contextMenu.js, lib/views/options.html
Words can be now marked as learnt
Words marked as learnt aren't translated
---- Minor Edits -----
- Changed note displaying hex values into rgba on the options page 
- Fixed bug causing empty values to be displayed on the options page
- Suggested changes in the class functions
=> Ability to mark words as learnt

lib/scripts/eventPage.js
enhancements to auto disable context menus
=> robust auto-disable context menu

lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js, lib/views/options.html
UI for difficulty buckets: user can add/delete words in difficulty buckets from the options page
Delete words in the difficulty buckets using the context menu 
Tooltip explaining the learnt words feature
Minor code refactoring
=> Improvements

lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js, lib/views/options.html
The user can save translations for future reference using the context menu and from the options page
=> Save translations

lib/scripts/mtw.js
This fix removes punctuation marks from filtered words.
=> fix punctuation marks in filtered words

.eslintrc, .jshintrc, lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/mtw.js, lib/views/options.html
This PR commits the following
1. User defined translations - Only one of the options can be chosen (Do not translate, user defined, active pattern)
2. Eslint - Linter settings for development
=> user defined translations and eslint

.eslintrc
Shows errors and warnings for **syntax and style errors**.
=> configure eslint

lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/utils/defaultStorage.js, lib/scripts/utils/saveFile.js, lib/views/options.html
This tab allows the user to backup, restore and reset configuration of Mind The Word. 
1. Downloads a text file on backup
2. Opens a dialog box to search for file on restore
3. Confirmation Modal for reset.
=> Reset config

lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/mtw.js, lib/views/options.html
=> Statistics tab [WIP]

lib/scripts/mtw.js, lib/views/options.html
=> Displaying character count as well for translator wise stats

lib/scripts/controllers/options.js, lib/scripts/mtw.js, lib/scripts/utils/defaultStorage.js, lib/views/includes/blacklist.html
This PR adds UI elements for users to change automatic blacklisting settings.
=> automatic blacklisting UI

lib/scripts/controllers/options.js, lib/scripts/mtw.js, lib/scripts/utils/defaultStorage.js, lib/views/includes/blacklist.html
This allows the user to turn on or off automatic blacklisting of word and websites.
=> automatic blacklisting toggle feature

lib/scripts/controllers/popup.js, lib/scripts/utils/defaultStorage.js
Adds functionality to automatically blacklist websites.
=> Auto blacklist websites

lib/scripts/controllers/options.js, lib/scripts/controllers/popup.js, lib/scripts/mtw.js, lib/scripts/utils/defaultStorage.js, lib/views/includes/quiz.html, lib/views/options.html
The quiz is generated out of randomly selected 10 words from the last set of translated words
=> [FEAT] Quiz mode

lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js
This PR adds functionality for easy whitelisting of websites through context menus. It automatically disables whitelist/blacklist menu depending on the page.
=> Easy whitelist

lib/scripts/controllers/options.js, lib/scripts/eventPage.js, lib/scripts/services/contextMenu.js
The user can see visual hints on google images before seeing the actual translation of the word. This will keep the user engaged and will keep him guessing. This will help the user in remembering the translations.
=> Visual hints

lib/scripts/controllers/options.js, lib/views/includes/translation.html
Warns the user if there is no key for the selected translator.
=> add no key alert

lib/scripts/services/yandexTranslate.js
I have limited the number of words per request to 500. The documentation does not show mention any limit. 
(closes #163)
=> fix yandex long URI error

lib/scripts/controllers/options.js, lib/styles/main.css, lib/views/includes/footer.html, lib/views/includes/translation.html
=> Fix issues

lib/scripts/eventPage.js
This fixes the commits which were reverted in #156
=> fix easy whitelisting

lib/scripts/controllers/options.js, lib/scripts/mtw.js, lib/scripts/utils/dateAndTimeHelpers.js, lib/scripts/utils/defaultStorage.js, lib/views/includes/stats.html, lib/views/includes/translation.html
Progress bar to show the daily and monthly Yandex API limits
The progress bar appears once 25% of the API limit is reached to prevent UI congestion 
After 100% of the API limit is reached a warning message is shown
=> Display daily and monthly yandex limits

lib/views/includes/advanced.html, lib/views/includes/blacklist.html, lib/views/includes/learning.html, lib/views/includes/translation.html
=> Added Youtube video tutorials

lib/scripts/mtw.js, lib/views/includes/translation.html
=> Minor changes

lib/scripts/mtw.js
=> closes #184
